### ISSUE TITLE
Folder tree navigation

### ISSUE THREAD

**Issue by kugiigi** [fredldotme/qmlcreator#2]
### Description
It would be cool if there's a folder tree navigation similar to Seabass.
In confined setup, it's fine to only have access to ~/.local/share/<appid>.
Perhaps you should also consider an unconfined version similar to Seabass.

**Comment by fredldotme** [comment]
QML Creator's project layout doesn't support subdirectories yet.
I'm probably not going to make the application unconfined in the forseeable future.

**Comment by fredldotme** [comment]
Adressed in commit ae6d150b8f85dd0fdf66e457a006a9aeef0f0a95
