### ISSUE TITLE
Enable swipe and mouse scrolling in the editor

### ISSUE THREAD

**Issue by kugiigi** [fredldotme/qmlcreator#3]
### Description
Currently, swiping in the editor selects texts and mouse scrolling does nothing.
I think it'll be better to enable swipe and mouse scrolling by default and just add a button to toggle text selection.

**Comment by fredldotme** [comment]
This will be hard to accomplish as it's hard for an app to distinguish between whether it's running in windowed mode or not. I could add a selection mode button to the header bar instead.

**Comment by kugiigi** [comment]
No need to detect windowed mode. Just enable scrolling via swipe and have a toggle for text selection via a button in the header :)
Then I think you can distinguish real mouse click and touch so maybe mouse scroll will work then dragging with mouse will enable text selection.

**Comment by fredldotme** [comment]
Keep in mind that this application is available on the Snap store for desktop users as well, so the default behavior would be specific to the Ubuntu Touch build.

**Comment by kugiigi** [comment]
I see but that makes it more sense to enable mouse scrolling right? or it already works in the desktop? At the moment it doesn't work on my Nexus 5. Only the scrollbar can scroll.

**Comment by fredldotme** [comment]
Mouse wheel support added with commit 663e10816ee3b117cb656cdf852d98f50c740a90
I'll take a look at touch scroll later.

**Comment by kugiigi** [comment]
Mouse scrolling works now however it looks like clicking via mouse doesn't work anymore in the editor.
Like for example positioning the cursor or selecting texts.

UPDATE: Hmmm...please ignore. I restarted my phone and the issue doesn't occur anymore. Mouse clicks are working. I wonder what cause though. I can't replicate anymore. I just remember that something weird happened where moving the mouse moves the scroll bar even if I'm not clicking on it. That was gone and the clicks stops working. oh well...

**Comment by fredldotme** [comment]
With commit 3cfd614 touch scrolling and selection should be working.

**Comment by fredldotme** [comment]
Fixed in 1.3.2
