### ISSUE TITLE
Switching between 2 files in 2 column layout overwrites the seleced file

### ISSUE THREAD

**Issue by kugiigi** [fredldotme/qmlcreator#4]
### Steps to reproduce
1. Opent the app and put it into 2 column layout (landscape or desktop mode)
2. Open a project.
3. Open a file
4. Click on another file on the list of project files.

### Expected Results
The editor will load the selected file's content.

### Actual Results
The same content is shown which is from the first selected file.
Switching between the 2 files will reveal that both files now have the same content.

### Additional Information
It seems that the content of the first file overwrites the newly selected file.

**Comment by fredldotme** [comment]
This should be fixed with commits c06b8bfbb4cc284eca380697b6cdab7efedadeb2 and 8e32172d742dcf5a5d1f6d7b6763113f637a8e94
Could you please test the current master with clickable, or do you need a click file?

**Comment by kugiigi** [comment]
I don't have clickable at hand at the moment so a ready click file would be good :)

**Comment by fredldotme** [comment]
Have a try.
[Uploading me.fredl.qmlcreator_1.3.1_armhf.zip…]()

**Comment by fredldotme** [comment]
[me.fredl.qmlcreator_1.3.1_armhf.zip](https://github.com/fredldotme/qmlcreator/files/3198484/me.fredl.qmlcreator_1.3.1_armhf.zip)

**Comment by kugiigi** [comment]
It works correctly now although the animation is less than ideal.The background is white when switching between 2 files unlike in normal pages where th current color/theme is used
